### ISSUE TITLE
Attrs... Attribute-wise "frozen"-specifier?

### ISSUE THREAD

**Issue by peteroconnor-bc** [python-attrs/attrs#623] opened 2020-02-11 22:02 UTC
I've found it's often best to use `@attrs(frozen=True, slots=True)` as a safe-default and only do otherwise when the situation requires.  

However, sometimes you have a state variable that needs to be updated.  In this case, it would be nice to have the option to still freeze variable other than the mutable state.  E.g. 

```
@attrs(slots=True)
class ExponentialMovingAverage(object):
    decay = attrib(type=float, frozen=True)  # Currently not an option
    avg = attrib(default=0)

    def __call__(self, x):
        self.avg = self.avg * (1 - self.decay) + x * self.decay
        return self.avg
```

Is there already a good way to do this that I'm missing?  If not, would it be a good addition?

This is obviously not that important for the example here, but becomes useful when classes get bigger and you want to prevent modification of a parameter that is supposed to be fixed.

**Comment by wsanchez** [comment] 2020-02-12 00:35
I think this is a duplicate of #133, yes?

**Comment by Julian** [comment] 2020-02-29 15:00
Seems like it to me too.

**Comment by hynek** [comment] 2020-03-04 15:32
Yep, a dupe. 👯‍♂️

**Closed by hynek** 2020-03-04 15:32 UTC
