### ISSUE TITLE
subclass registration of generic decorator class fails

### ISSUE THREAD

**Issue by Darkdragon84** [python-attrs/attrs#1364] opened 2024-10-25 10:36 UTC
I am using the decorator pattern to create a decorator class `Decorated` from an abstract base class `Base`.

```python
from attrs import define

@define
class Base:
    @abstractmethod
    def meth(self): ...

@define
class Decorated(Base):
    base: Base

    def meth(self): pass
```
`Base` has many more subclasses in addition and I use it as annotation in many places, so I would like to be able to register all subclasses of it to the converter. This works fine in the above example by e.g.
```python
from cattrs import Converter
from cattrs.strategies import include_subclasses

converter = Converter()
include_subclasses(Base, converter)
```

However, I would now like to make `Decorated` generic on subclasses of `Base`:
```python
from typing import Generic, TypeVar

@define
class Decorated(Base, Generic[T]):
    base: T

    def meth(self): pass
```
Now, when registering all subclasses of `Base` I get the error
```
cattrs.errors.StructureHandlerNotFoundError: Missing type for generic argument T, specify it when structuring.
```
This happens at registration time, not at (un)structuring time.

Is this expected? Can this be mitigated/circumvented?

**Comment by hynek** [comment] 2024-10-26 05:09
dupe of https://github.com/python-attrs/cattrs/issues/595

**Closed by hynek** 2024-10-26 05:09 UTC
