### ISSUE TITLE
Example of initialsing base class in a derived class

### ISSUE THREAD

**Issue by BrendanSimon** [python-attrs/attrs#167] opened 2017-03-17 12:09 UTC
If I have a class hierarchy using attrs, how do I initialise the parent class ?

Normally the constructor would call `super().__init__()` right?  How is this done with attrs classes?

Could you provide and example in the examples documentation please :)

**Comment by BrendanSimon** [comment] 2017-03-17 12:22
Hmmm, I found the "How Does It Work?" documentation, which states that attrs never calls `super()` and that it walks the class hierarchy to collect the attributes of the super classes.

Still a good example would be good :)

**Comment by Tinche** [comment] 2017-03-17 12:25
Yeah, if all your bases are attrs classes without `__attrs_post_init__`, you don't have to do anything. For everything else, there's `__attrs_post_init__`.

**Comment by BrendanSimon** [comment] 2017-03-18 06:00
How do you initialise a base class attribute with a different value?

e.g. base class has member `x` with default of `0` (via `attr.ib`), and sub-class wants to intialise `x` to a different value (e.g. `123`).

I tried using `attr.ib` with default, but it seem to add an additional member (i.e. there seemed to be 2 members named `x`).

I did try `def __attrs_post_init__():` in sub-class and set the attribute directly, and that didn't seem to create an extra member.  Is that the right thing to do?  Does that just create a new name?  Maybe I should use `super().x = 123`?  I presume that works - I've not used `super()` much.

**Comment by hynek** [comment] 2017-03-20 10:53
Generally speaking, we believe that subclassing for object composition is a [bad thing](https://www.youtube.com/watch?v=3MNVP9-hglc), therefore attrs doesn’t have explicit support for many things that it entails.

That said, getting two members `x` in your case looks like a bug to me and should be fixed.  Would you mind posting a bug with an example?  Thank you!

**Closed** 2017-05-10 08:37 UTC

**Comment by felipedau** [comment] 2017-08-21 16:03
A while ago I was asking this same question. I was not looking for a way to overwrite an attribute, but just call `super().__init__()` - the attrs class I was creating was a subclass of `Thread` and that had to be called.

As I continued learning what I was doing, I noticed a thread was not needed anymore (and therefore the inheritance), but I'm still curious: how to initialize the parent class with attrs? It seems there are two cases:

1. When subclassing a non-attrs class, call `super().__init__()` in the subclass' `__attrs_post_init__()`
2. When subclassing an attrs class, call `super().__attrs_post_init__()` in the subclass' `__attrs_post_init__()`

Is that correct?

Thanks!

**Comment by hynek** [comment] 2017-08-30 08:43
Looks correct, yes.  Calling `super().__init__()` in the second case probably would work too but it would unnecessarily re-initialize the attributes it knows about.

**Comment by felipedau** [comment] 2017-08-30 15:54
The reason I called `__attrs_post_init__()` in the second case was not to prevent redundancy (although that is also a good reason), but because `__init__()` results in a recursion until a `RuntimeError` is raised.

I did not mention that at first because I thought that was the wrong way to do it. I thought that `super().__init__()` would call the subclass' `__attrs_post_init__()` in the end, making it call itself.

Now that you mentioned and after thinking a second time, I think that behavior is actually wrong. `super().__init__()` shouldn't call the subclass' `__attrs_post_init__()` and in fact never calls the superclass' `__attrs_post_init__()`. Reproducing:

```python
import attr


a_post_init_called = False


@attr.s
class A(object):
    a = attr.ib()

    def __attrs_post_init__(self):
        global a_post_init_called
        a_post_init_called = True


b_post_init_called = False


@attr.s
class B(A):
    b = attr.ib()

    def __attrs_post_init__(self):
        global b_post_init_called
        b_post_init_called = True

        super().__init__('')


try:
    b = B('a', 'b')
except Exception as e:
    print(e)


print('post inits called: {}, {}'.format(a_post_init_called,
                                         b_post_init_called))
```

output:

```
maximum recursion depth exceeded while calling a Python object
post inits called: False, True
```

(I passed `''` just to show that passing `self.a` would not cause the problem.)

Just to clarify: I do not think that using attrs like this is correct and I am not asking you to provide anything to support code like this. I am just reporting something that seems wrong.

**Comment by VideoPlayerCode** [comment] 2019-09-29 03:21
To summarize: If you subclass from another attrs class, the subclass collects all attributes from the parent class hierarchy, and from itself, and generates a brand new `__init__` which accepts all merged attributes from all classes (you can verify that with `inspect.signature(thesubclass.__init__)`).

But if your superclass did some special `__attrs_post_init__` work, then be aware that the rules are as follows:

- If your subclass DOES NOT HAVE its own `__attrs_post_init__`, then the execution is as follows: The subclass runs its own `__init__` (which does the attrs work of validating and initializing variables), and then it attempts to call `__attrs_post_init__` and calls the PARENT class one!
- If your subclass DOES have its own `__attrs_post_init__` (meaning there was one in both your superclass and subclass), then the execution is as follows: The subclass runs its own `__init__`, which then runs its own `__attrs_post_init__`. It will NOT automatically call the superclass post-init function. So it is YOUR JOB to call `super().__attrs_post_init__()`

Demonstration of all cases:

```python
@attr.s
class A:
    a = attr.ib()
    def __attrs_post_init__(self):
            print('a hello')

@attr.s
class B(A): # Because this class has a post-init, only THIS post-init will run.
    b = attr.ib()
    def __attrs_post_init__(self):
            super().__attrs_post_init__() # Without manually calling, A's post-init wouldn't run.
            print('b hello')

@attr.s
class C(A): # Because this class lacks a post-init, the one from A will run instead.
    c = attr.ib()
```

Result in python console:

```
>>> A(1)
a hello
A(a=1)

>>> B(1,2)
a hello
b hello
B(a=1, b=2)

>>> C(1,2)
a hello
C(a=1, c=2)
```

Of course, in hindsight, perhaps attr should have been coded so that its `__init__` function checks for `super().__attrs_post_init__` and if so runs it first, and THEN runs the current class's own `__attrs_post_init__`. So that both of them are automatically run in the correct order.

But it's way too late to change that design now, since most people have code now that manually calls the superclass post-init function as shown in example B above.

And there's a good argument for the way things are designed, because it means that YOU decide if you want the superclass `__attrs_post_init__` to run or not. So I don't really dislike this design. It's fine.

I just wanted to document everything. Thanks @hynek @felipedau @BrendanSimon for all your info in this thread.
