### ISSUE TITLE
Change defaults of an 3rd party attrs class

### ISSUE THREAD

**Issue by tc8** [python-attrs/attrs#829] opened 2021-06-29 21:41 UTC
I'm using the [grafanalib library](https://github.com/weaveworks/grafanalib/blob/master/grafanalib/core.py#L384) which uses attrs extensively and one of the class looks something like this

```
@attr.s
class Target(object):
    intervalFactor = attr.ib(default=2)
...
```

I want to change the default of `intervalFactor` to `1`. I could specify `1` each time in the constructor but that's very tedious when I have to do it each time. 

I tried subclassing it and playing with `__attrs_pre_init__ `, `__attrs_post_init__ `, and `__attrs_init__ ` but could not find any combination that gave me the desired behavior. 

I've also looked at using `attr.evolve` like `attrs.evolve(default_target, myarg1, myarg2, ...)` where default_target is a Target instance with the default values set. This works but witing `attrs.evolve(default_target` each time in lieu of the constructor is tedious. 

I could wrap it in a helper function, like 
```
def create_target(*args, **kwargs) -> Target: 
  return attrs.evolve(default_target, *args, **kwargs)
```
The problem with this is that I lose the IDE (PyCharm) autocompletion that I would get with writing `attrs.evolve(...)` manually. 

I tried setting the `__signature__` manually by doing `create_target.__signature = inspect.signature(Target.__init__)` but this didn't give me the correct tooltip in the editor model. 

Any help would be greatly appreciated. 

** On a related note**
How is `attrs.evolve` able to provide the right auto-complete suggestions in PyCharm? Is it because of the built-in integration with PyCharm?

**Comment by hynek** [comment] 2021-06-30 06:32
> I'm using the [grafanalib library](https://github.com/weaveworks/grafanalib/blob/master/grafanalib/core.py#L384) which uses attrs extensively and one of the class looks something like this
> 
> ```
> @attr.s
> class Target(object):
>     intervalFactor = attr.ib(default=2)
> ...
> ```

This should work:

```python
@attr.define
class MyTarget(Target):
    intervalFactor = attr.field(default=1)
```

The only downside is that the order of the arguments changes. But that shouldn't be a problem if you don't want to pass it anyway.

> ** On a related note**
> How is `attrs.evolve` able to provide the right auto-complete suggestions in PyCharm? Is it because of the built-in integration with PyCharm?

I think so. PyCharm has added attrs support a long time ago so I wouldn't be surprised by advanced features.

**Comment by tc8** [comment] 2021-06-30 06:38
Hi @hynek ,

Thank you for your response.

How would you handle cases where the field specifies other parameters like validator, converter, etc. 
In your suggestion, I would need to copy the full declaration of the field, including the other parameters. That introduces some risk since my declaration and the source can go out of sync. 
Is there another way where I can be agnostic of the other field parameters and override only the default?

**Comment by hynek** [comment] 2021-06-30 06:46
That seems like a duplicate of #637

You can somewhat work around it by introspecting Target using `attr.fields` and use the data from there.

However, if you just want to stop passing parameters to a class, I'd suggest to write a classmethod or a function and be done with it:

```python
def make_target() -> Target:
    return Target(intervalFactor=1)
```

**Comment by tc8** [comment] 2021-06-30 18:16
Thanks, I didn't know about #637 

A hacky solution I came up with is

```
def new_attrib(attrib: attr.Attribute, new_default: Any):
    attrib = attrib.evolve(default=new_default)

    attr_dict = {
        name: getattr(attrib, name) if name != "metadata" else dict(attrib.metadata)
        for name in attrib.__slots__
        if name not in ("name", "eq_key", "order_key", "inherited")
    }
    return attr.ib(**attr_dict)

@attr.s
class DefaultTarget(Target):
    intervalFactor = new_attrib(attr.fields(Target).intervalFactor, 1)
```

Unfortunately, I can't assign `intervalFactor` to `Attribute` directly. Instead, I have to go through `attr.ib`, which produces a `_CountingAttr`. Is there a cleaner way to do this than what I did?

**Comment by yunduz** [comment] 2021-07-02 17:11
I am also looking for a solution to overwrite default values. The above seems to work but would be cool if it was part of the attrs library.

**Comment by hynek** [comment] 2021-07-03 09:44
Since `Attribute` has an `evolve()` method I think it would make sense to add a `.to_field()` too.

**Comment by wsanchez** [comment] 2021-08-23 15:02
@hynek Would `.to_field` be covered in #637 or is this now a separate ticket for that?

**Comment by hynek** [comment] 2021-08-29 08:26
I guess?

I'm not sure whether this wouldn't be too clunky:

```python
attr.fields(Target).intervalFactor.evolve(default=1).to_field()
```

OTOH it's the least magical way to achieve that.

**Comment by peteroconnor-bc** [comment] 2021-12-13 16:22
Would sure be nice to support 
```
@attr.s
class DefaultTarget(Target):
     intervalFactor = Target.intervalFactor.evolve(default=1)
```

**Comment by hynek** [comment] 2021-12-28 07:39
Closing in favor of #637, please subscribe there if you want to be kept up-to-date.

**Closed by hynek** 2021-12-28 07:39 UTC
