### ISSUE TITLE
slots=True classes are not weak-referenceable

### ISSUE THREAD

**Issue by gmacon** [python-attrs/attrs#174] opened 2017-03-30 17:50 UTC
This code:

```
import weakref
import attr

@attr.s(slots=True)
class Foo(object):
    x = attr.ib()

weakref.ref(Foo('x'))
```

produces this error:

```
Traceback (most recent call last):
  File "slotsref.py", line 8, in <module>
    weakref.ref(Foo('x'))
TypeError: cannot create weak reference to 'Foo' object
```

In the docs for *\_\_slots\_\_*, it says "Without a *\_\_weakref\_\_* variable for each instance, classes defining *\_\_slots\_\_* do not support weak references to its instances. If weak reference support is needed, then add `'__weakref__'` to the sequence of strings in the *\_\_slots\_\_* declaration."

Adding `'__weakref__'` to the list isn't hard, but I wanted to see if people had any opinions about whether this should happen transparently, or if you should have to opt-in to it by saying `@attr.s(weakref=True)`.

**Comment by Tinche** [comment] 2017-03-30 20:14
It should be opt-in, just like it's opt-in for normal slot classes. No sense in wasting a slot by default for something that's pretty niche. I agree we should support it somehow.

Not a fan of `attr.s(weakref=True)`. The parameter doesn't make sense for dict classes and it makes our main user-facing API more complex for, again, arguably a niche feature.

You can work around the limitation today, by defining `__weakref__` yourself, explicitly.
```
import weakref
import attr


@attr.s(slots=True)
class A:
    a = attr.ib()
    __weakref__ = attr.ib(init=False, hash=False, repr=False, cmp=False)

weakref.ref(A(1))
```
This is ugly but it works fine. It's also kind of logical I think, because this is exactly the `attrs` equivalent of adding `__weakref__` to slots directly like you'd do if you weren't using attrs. The first step could be just documenting this in the docs for slot classes.

We could make it a little prettier with a wrapper:
```
import weakref
import attr


@attr.s(slots=True)
class A:
    a = attr.ib()
    __weakref__ = attr.weakref_attrib()

weakref.ref(A(1))
```

Another thing we could do is enable users to define their own `__slots__`, and just append to that, instead of generating the entire `__slots__` ourselves. Then you could do:
```
import weakref
import attr


@attr.s(slots=True)
class A:
    __slots__ = ('__weakref__')
    a = attr.ib()

weakref.ref(A(1))
```

This is completely in the spirit of `attrs`, I think. You define the class just the way you want it, and `attrs` adds to that.

**Comment by njsmith** [comment] 2017-09-30 20:52
FWIW, I'd like to put in a vote for some sort of built-in support inside the `attr.s` call, like `weakrefable=True` or something, and a weaker vote for making `True` the default.

With the current design, `slots=True` is pretty much always better (and the docs recommend it be used more-or-less by default), but then it has this unexpected semantic consequence compared to regular classes. It seems nicer to me if toggling `slots=` doesn't automatically have this seemingly-unrelated effect on the class's public API. It's not such a big deal for private code inside an organization because you can add weakref support as and when needed, but if you use attrs to define classes in a public API then [it can lead to surprising bug reports](https://github.com/python-trio/trio/issues/331).

And then to fix it, you have to do this [rather cumbersome thing](https://github.com/python-trio/trio/pull/337/files) where the `slots=True` and the `__weakref__ = weakref_attrib()` are at different places in the code – possibly widely separated if you have a long docstring – yet have to be managed together and kept in sync.

**Comment by njsmith** [comment] 2017-09-30 21:00
Oh, whoops, it's actually much worse... the `__weakref__ = attr.ib(...)` trick described above [doesn't work at all on pypy3](https://travis-ci.org/python-trio/trio/jobs/281747188). (I haven't tried pypy2.)

Reproducer:
```python
import attr

@attr.s(slots=True)
class Blah:
    some_attr = attr.ib()
    __weakref__ = attr.ib(init=False, hash=False, repr=False, cmp=False)
```

Runs fine on CPython, but on PyPy3 5.8.0 I get:

```
~$ ~/pypy/pypy3.5-5.8-beta-linux_x86_64-portable/bin/pypy3 /tmp/attrs-with-slots.py              
Traceback (most recent call last):
  File "/tmp/attrs-with-slots.py", line 3, in <module>
    @attr.s(slots=True)
  File "/home/njs/pypy/pypy3.5-5.8-beta-linux_x86_64-portable/site-packages/attr/_make.py", line 340, in wrap
    _transform_attrs(cls, these)
  File "/home/njs/pypy/pypy3.5-5.8-beta-linux_x86_64-portable/site-packages/attr/_make.py", line 210, in _transform_attrs
    setattr(cls, a.name, a)
AttributeError: readonly attribute
```
(I also got the same result on a recent pypy3 nightly.)

More details on the offending `setattr` call:
```
(Pdb) p cls
<class '__main__.Blah'>
(Pdb) p a.name
'__weakref__'
(Pdb) p a
Attribute(name='__weakref__', default=NOTHING, validator=None, repr=False, cmp=False, hash=False, init=False, convert=None, metadata=mappingproxy({}))
```

**Comment by njsmith** [comment] 2017-09-30 21:04
PyPy version of the bug: https://bitbucket.org/pypy/pypy/issues/2670/inconsistency-between-pypy-and-cpython-in

**Comment by hynek** [comment] 2018-01-17 11:04
closing in favour of #325

**Closed by hynek** 2018-01-17 11:04 UTC
