### ISSUE TITLE
TypeError when using super() and slots=True

### ISSUE THREAD

**Issue by p-himik** [python-attrs/attrs#102] opened 2016-09-28 11:30 UTC
This code

``` python
import attr


@attr.s(slots=True)
class A:
    def f(self):
        pass


@attr.s(slots=True)
class B(A):
    def f(self):
        super().f()


B().f()
```

results in this error

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    B().f()
  File "test.py", line 13, in f
    super().f()
TypeError: super(type, obj): obj must be an instance or subtype of type
```

If I use `super(B, self)`, everything works just fine.

**Comment by Tinche** [comment] 2016-09-28 11:56
Huh, interesting. Slots are a little tricky since we can't "add" slots to a class that's already defined, so we switch the class with another one in ``attr.s``. This is what's probably causing the problem.

I need to figure out how to debug this :)

**Comment by p-himik** [comment] 2016-09-28 12:10
I guess that some other more intricate workflow involving `isinstance` will be broken in this case too.
May'be it's possible to switch the parent class with the updated one?

**Comment by Tinche** [comment] 2016-09-28 12:19
Reading up on it a little (https://www.python.org/dev/peps/pep-3135/), there will probably be problems with any function inside the class using ``__class__`` or no-arg ``super()``. (Have to admit I wasn't even aware the ``__class__`` name was available inside of methods.)

Unfortunately these function cells that contain the reference to the enclosing class appear to be immutable.

Anything outside the class should be fine.

At the very least, it will be possible to raise an informative error at class definition time.

More research needed.

**Comment by moshez** [comment] 2016-09-28 22:42
Just my obsession with minimal example: notice that this reproduces even in this simpler example:

    import attr

    class A:
        pass

    @attr.s(slots=True)
    class B(A):
        def f(self):
            super()

    B().f()

**Comment by hynek** [comment] 2016-09-29 08:57
Something tells me that this might be unsolvable unless there’s some secret backdoor we can use. :|

**Comment by moshez** [comment] 2016-09-29 13:49
Perhaps the only way is to error out if any of the functions inside the class refer to "super" or "__class__" with an explanation.

**Comment by perkinslr** [comment] 2016-10-10 01:35
Could do it by recreating the function objects, the function cells are immutable, but creating a duplicate function object which contains a cell pointing to the new class is possible.  Unfortunately, explicitly creating `cell` instances from python (à la `types.FunctionType()`) is not possible, so it would require including a stub method in the new type that references the cell and then creating a new function using the old parameters except for swapping the closure.

It's also possible via the python C API to set the cell contents, which may be the simplest solution.  I've tested it a bit and it seems to work.  

    class A(object):
        def printClass(self):
            print(__class__)

    class NewA(object):
        pass

    import ctypes
    libpython = ctypes.cdll.LoadLibrary('/usr/lib64/libpython3.5.so')
    libpython.PyCell_Set(ctypes.py_object(A.printClass.__closure__[0]), ctypes.py_object(NewA))

    A().printClass()

It would require figuring out if the cell holds a weakref or a normal reference to the cell contents, so as to not screw up the reference count.

**Comment by hynek** [comment] 2016-10-13 07:45
I wonder if we couldn’t fix this using `__new__` once we drop the requirement, that attrs definitions are replaced by `Attribute` instances (since class attributes on `__slots__` classes are immutable).

**Comment by p-himik** [comment] 2017-01-03 16:05
Just got bitten by it again - only this time while using a metaclass.

But we can add `__slots__` in a metaclass *and* according to https://stackoverflow.com/questions/11091609/setting-a-class-metaclass-using-a-decorator you can add a metaclass by using a decorator.
So what if `@attr.s(...)` instead of directly altering class attributes and/or the class itself, would just add a metaclass, taking already provided metaclass into account?

**Comment by p-himik** [comment] 2017-01-03 16:40
Hmm, this method still doesn't make `TypeError` go away, although the same error doesn't happen when using `metaclass` kwarg when creating a class.
Probably it's possible to create a metaclass that would be used in `@attr.s(...)` when a user doesn't need `super()` and used as a regular metaclass when there's a need to `super()`.

**Comment by hynek** [comment] 2017-07-27 12:33
Yay, I just ran into the problem too. :|

Currently we have problems on both sides of the fence:

- If we replace the class, super() stops working
- If we don’t, a bunch of other assumptions don’t work like #202 

Looks like a lose-lose scenario. :|

**Comment by Tinche** [comment] 2017-07-27 13:50
There's a way to fix this on CPython.

Content warning: hairy code ahead ;)

Simplest reproducer:

```
import attr


@attr.s(slots=True)
class C:
    a = attr.ib()

    def t(self):
        return __class__


>>>print(C(1).t() is C)
False
```

The problem is this:
```
>>> C.t.__closure__[0].cell_contents
<class '__main__.C'>   # This is not our class, but the old class.
```

The fix:
```
mport attr


@attr.s(slots=True)
class C:
    a = attr.ib()

    def t(self):
        return __class__

import ctypes
PyCell_Set = ctypes.pythonapi.PyCell_Set
PyCell_Set.argtypes = (ctypes.py_object, ctypes.py_object)
PyCell_Set.restype = ctypes.c_int
PyCell_Set(C.t.__closure__[0], C)

>>> print(C(1).t() is C)
True
```

We need to ask our PyPy friends how to handle this on PyPy, though.

**Comment by hynek** [comment] 2017-07-27 14:12
That’s…disgusting. :D

I’d know whom to ask however maybe we should discuss what the canonical answer in attrs should be: always new class (like slots=True, requires interpreter internals) or patched class (classic, requires potentially meta classes to be done properly—I intend to look at a `__new__`-based approach once we’re rid of .Attribute access)?

Yesterday I’d have said “always new class” but the repercussions seem worse than patching around.

**Comment by Tinche** [comment] 2017-07-27 14:19
I don't actually know how a metaclass approach would work. Could you show me a prototype just for me to get the gist?

**Comment by hynek** [comment] 2017-07-27 15:14
Haven’t tried anything yet but you can set `__slots__` in `__new__`.   I hope to remember, that the reason why we can’t do it, is that currently the slots are filled and thus immutable.

**Comment by Tinche** [comment] 2017-07-27 22:17
Alright, got a response from the PyPy team (Armin Rigo of course :)

It's actually easier there:

```
C.t.__closure__[0].__setstate__((C,))
```

**Comment by hynek** [comment] 2017-08-03 15:12
Fixed by #226

**Closed by hynek** 2017-08-03 15:12 UTC

**Comment by radugrosu** [comment] 2020-06-12 12:54
This still happens on 19.3.0, for `property`s.

**Comment by wsanchez** [comment] 2020-06-12 18:56
@radugrosu Would you mind opening a new ticket with an example?

**Comment by radugrosu** [comment] 2020-06-12 20:53
> @radugrosu Would you mind opening a new ticket with an example?

Done.
