### ISSUE TITLE
How Name Mangling is supposed to work in python-attrs? (double leading underscores)

### ISSUE THREAD

**Issue by txemi** [python-attrs/attrs#927] opened 2022-03-05 10:38 UTC
Converting some classes to atts I found that there is not a documented way to work with name mangling. I am aware of pythonic way in wich forcing is not common, trusting responsible adults instead it is and name mangling is not commonly used; but anyway I sometimes use it for preventing accidents where it is clear that some data should not be accesed from outside the class.

What has python-atts to say about this? (Direct approach does not work, I already tried and constructor with keyword fails with "TypeError: missing a required argument")

**Comment by hynek** [comment] 2022-03-09 10:21
`attrs` automatically removed leading underscores when determining the argument names: https://www.attrs.org/en/stable/init.html#private-attributes

**Comment by txemi** [comment] 2022-03-10 19:56
Sorry, I did not undertand. May I use this?

`@define
class C:
   __x: int`

It did not work when I tried to init __x from constructor.

> `attrs` automatically removed leading underscores when determining the argument names: https://www.attrs.org/en/stable/init.html#private-attributes

**Comment by hynek** [comment] 2022-03-11 06:51
Ah yeah I'm sorry I misread on my phone an answered from memory.

This is in fact currently not supported and is a dupe of #619.

As you wrote, using name mangling is rather uncommon nowadays, so nobody came forward to push for a proper implementation.

**Comment by wbolster** [comment] 2022-03-21 17:13
closing as dup to keep discussion centralized; see #619

**Closed by wbolster** 2022-03-21 17:13 UTC
